// Export helpers (Step 5c): CSV, ICS, and PDF generation with safe filenames.
import PDFDocument from 'pdfkit';

export function safeFilename(base, ext) {
  const clean = String(base)
    .replace(/[^a-zA-Z0-9-_ ]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 80) || 'opus-export';
  const stamp = new Date().toISOString().slice(0, 10);
  return `${clean}-${stamp}.${ext}`;
}

function csvCell(value) {
  const s = value == null ? '' : String(value);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function toCsv(rows, columns) {
  const header = columns.map((c) => csvCell(c.label)).join(',');
  const body = rows
    .map((row) => columns.map((c) => csvCell(typeof c.value === 'function' ? c.value(row) : row[c.value])).join(','))
    .join('\n');
  return `${header}\n${body}\n`;
}

function icsDate(value) {
  const d = new Date(value);
  return d.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
}

export function toIcs(events, { calendarName = 'OPUS' } = {}) {
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//OPUS//Job Portal//EN',
    `X-WR-CALNAME:${calendarName}`
  ];
  for (const e of events) {
    if (!e.startsAt && !e.date) continue;
    const start = e.startsAt || `${e.date}T${e.time || '09:00'}:00Z`;
    const end = e.endsAt || new Date(new Date(start).getTime() + 60 * 60 * 1000).toISOString();
    lines.push(
      'BEGIN:VEVENT',
      `UID:${e.id || Math.random().toString(36).slice(2)}@opus`,
      `DTSTAMP:${icsDate(new Date())}`,
      `DTSTART:${icsDate(start)}`,
      `DTEND:${icsDate(end)}`,
      `SUMMARY:${(e.title || e.summary || 'OPUS Event').replace(/\n/g, ' ')}`,
      `DESCRIPTION:${(e.notes || '').replace(/\n/g, ' ')}`,
      `LOCATION:${(e.location || '').replace(/\n/g, ' ')}`,
      'END:VEVENT'
    );
  }
  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

// Render a simple, professional PDF and return a Buffer.
export function toPdf({ title, subtitle, sections = [] }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      doc.fontSize(20).fillColor('#4c1d95').text('OPUS', { continued: false });
      doc.moveDown(0.2);
      doc.fontSize(16).fillColor('#0f172a').text(title || 'Report');
      if (subtitle) doc.fontSize(10).fillColor('#64748b').text(subtitle);
      doc.moveDown();

      for (const section of sections) {
        if (section.heading) {
          doc.moveDown(0.5).fontSize(13).fillColor('#0f172a').text(section.heading);
          doc.moveDown(0.3);
        }
        for (const line of section.lines || []) {
          doc.fontSize(10).fillColor('#334155').text(line);
        }
      }

      doc.moveDown(2).fontSize(8).fillColor('#94a3b8')
        .text(`Generated by OPUS on ${new Date().toISOString().slice(0, 19).replace('T', ' ')} UTC`);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
